# Generated by Django 5.1.1 on 2024-11-09 09:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=32, unique=True),
        ),
    ]
