# Generated by Django 5.1.1 on 2024-11-09 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default=uuid.uuid4, max_length=32, unique=True),
        ),
    ]
