# Generated by Django 5.1.1 on 2024-11-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('fertile_start', models.DateField()),
                ('fertile_end', models.DateField()),
                ('ovulation', models.DateField()),
                ('predicted_period_start', models.DateField()),
                ('predicted_period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
